### PR TITLE
move from Requires to extensions on 1.9

### PR DESCRIPTION
**Pull request by KristofferC**
I didn't run the tests because SymEngine fails to build on an mac M1.

### CODE REVIEW

**Comment by KristofferC** [comment]
Tests seem to run with very old versions of packages. 

```
(jl_QaRzuP) pkg> st -m --outdated
Status `/private/var/folders/tp/2p4x9ygx48sgsdl1ccg1mp_40000gn/T/jl_QaRzuP/Manifest.toml`
⌃ [79e6a3ab] Adapt v3.6.0 (<v3.6.1)
⌅ [4fba245c] ArrayInterface v2.14.17 (<v7.2.1): DiffEqBase, DiffEqJump, LabelledArrays, RecursiveArrayTools
⌅ [324d7699] CategoricalArrays v0.7.7 (<v0.10.7): DataFrames
⌅ [d360d2e6] ChainRulesCore v0.9.45 (<v1.15.7): DiffEqBase
⌅ [34da2185] Compat v3.46.1 (<v4.6.1): CategoricalArrays, ChainRulesCore, DataFrames, DiffEqBiological, DiffEqJump, SymEngine
⌃ [187b0558] ConstructionBase v1.4.1 (<v1.5.1)
⌃ [a93c6f00] DataFrames v0.20.0 (<v1.5.0)
⌅ [864edb3b] DataStructures v0.17.20 (<v0.18.13): DiffEqBiological
⌃ [2b5f629d] DiffEqBase v6.44.3 (<v6.122.1)
⌃ [eb300fae] DiffEqBiological v3.11.0 (<v4.3.0)
⌅ [c894b116] DiffEqJump v6.10.0 (<v8.6.3): DiffEqBiological
⌅ [ffbed154] DocStringExtensions v0.8.6 (<v0.9.3): DiffEqBase
⌅ [497a8b3b] DoubleFloats v0.9.1 (<v1.2.3): HomotopyContinuation
⌅ [7c1d4256] DynamicPolynomials v0.3.21 (<v0.4.6): DiffEqBiological, HomotopyContinuation
⌅ [c145ed77] GenericSchur v0.4.1 (<v0.5.3): DoubleFloats
⌅ [f213a82b] HomotopyContinuation v1.2.1 (<v2.8.0): DiffEqBiological
⌅ [42fd0dbc] IterativeSolvers v0.8.5 (<v0.9.2): DiffEqBase
⌃ [2ee39098] LabelledArrays v1.6.6 (<v1.14.0)
⌅ [e6f89c97] LoggingExtras v0.4.9 (<v1.0.0): DiffEqBase
⌅ [e1d29d7a] Missings v0.4.5 (<v1.1.0): CategoricalArrays, DataFrames
⌅ [291d046c] MixedSubdivisions v0.3.4 (<v1.1.2): HomotopyContinuation
⌅ [102ac46a] MultivariatePolynomials v0.3.18 (<v0.4.7): DynamicPolynomials, FixedPolynomials, HomotopyContinuation, MixedSubdivisions
⌅ [d8a4904e] MutableArithmetics v0.2.22 (<v1.2.3): DynamicPolynomials, MultivariatePolynomials
⌅ [f27b6e38] Polynomials v0.8.0 (<v3.2.7): DoubleFloats
⌅ [2dfb63ee] PooledArrays v0.5.3 (<v1.4.2): DataFrames
⌅ [08abe8d2] PrettyTables v0.6.0 (<v2.2.2): HomotopyContinuation
⌃ [be4d8f0f] Quadmath v0.5.6 (<v0.5.8)
⌅ [3cdcf5f2] RecipesBase v0.7.0 (<v1.3.3): DiffEqBiological, SymEngine
⌃ [731186ca] RecursiveArrayTools v2.7.2 (<v2.38.0)
⌅ [f2c3362d] RecursiveFactorization v0.1.0 (<v0.2.18): DiffEqBase
⌅ [189a3867] Reexport v0.2.0 (<v1.2.2): CategoricalArrays, DataFrames, DiffEqBiological, PrettyTables
⌅ [f2b01f46] Roots v1.4.1 (<v2.0.10): DiffEqBase
⌅ [efcf1570] Setfield v0.8.2 (<v1.1.1): Roots
⌅ [a2af1166] SortingAlgorithms v0.3.2 (<v1.1.0): DataFrames
⌅ [276daf66] SpecialFunctions v0.10.3 (<v2.2.0): DoubleFloats, SymEngine
⌅ [90137ffa] StaticArrays v0.11.1 (<v1.5.17): DiffEqBase, DiffEqJump, HomotopyContinuation, MixedSubdivisions, RecursiveArrayTools
⌅ [123dc426] SymEngine v0.7.1 (<v0.8.7): DiffEqBiological
⌅ [bd369af6] Tables v0.2.11 (<v1.10.0): DataFrames, PrettyTables
```

**Comment by ChrisRackauckas** [comment]
tests are using DiffEqBiological but should be using Catalyst.

**Comment by chriselrod** [comment]
@korsbo ?

**Comment by vtjnash** [comment]
bump?

**Comment by vtjnash** [comment]
Replaces https://github.com/korsbo/Latexify.jl/pull/245?

**Comment by KristofferC** [comment]
Hadn't seen that heh

**Comment by gustaphe** [comment]
Sorry about the delay in replies here. I'd be comfortable merging either of this or #245, but I don't know if there is any difference apart from a couple of style choices. Can any of you spot anything?

**Comment by gustaphe** [comment]
Closed with #245

**Pull request closed without merging**
